name: Log Requests to Google Sheets

on:
  schedule:
    - cron: '*/1 * * * *'  # Har 14 minute me chalega

jobs:
  log-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request and Log Response
        run: |
          START=$(date +%s%N)
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://design-challenge-syoc.onrender.com/)
          END=$(date +%s%N)
          RESPONSE_TIME=$(( (END - START) / 1000000 ))  # Milliseconds me convert karega

          curl -X POST "https://script.google.com/macros/s/AKfycbyoJ_MCMwtyrZ6RHfj-Wj-L5fAixUfbUJoXwwwqH6BvRpWDauwz0j-1ccuREhoFCAkW/exec" \
               -H "Content-Type: application/json" \
               -d "{\"responseTime\": $RESPONSE_TIME, \"responseData\": \"$RESPONSE\"}"
